//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elevi
    {
        public string NUME { get; set; }
        public Nullable<int> VARSTA { get; set; }
        public string EMAIL { get; set; }
    }
}
